groups:
- name: application_alerts
  rules:
  - alert: ApplicationDown
    expr: up{job="react-app"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "React application is down"
      description: "The React application has been down for more than 30 seconds."

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 5 minutes."

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 90% for more than 5 minutes."